spring:
  application:
    name: Identity-And-Access-Control-Server
  datasource:
    url: jdbc:postgresql://ep-white-mountain-a2jkrsx3.eu-central-1.aws.neon.tech/google-club?sslmode=require
    username: google-club_owner
    password: wrSROK5eA4vN
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
