spring:
  application:
    name: Identity-And-Access-Control-Server
  datasource:
    url: jdbc:postgresql://ep-white-mountain-a2jkrsx3.eu-central-1.aws.neon.tech/google-club?sslmode=require
    username: google-club_owner
    password: wrSROK5eA4vN
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false


app:
  CORS:
    ALLOWED-ORIGINS: ${CORS_ALLOWED_ORIGINS:*}
    ALLOWED-METHODS: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
    ALLOWED-HEADERS: ${CORS_ALLOWED_HEADERS:*}
    EXPOSED-HEADERS: ${CORS_EXPOSED_HEADERS:*}
    ALLOW-CREDENTIALS: ${CORS_ALLOW_CREDENTIALS:true}
    MAX-AGE: ${CORS_MAX_AGE:3600}
  depServers: ${DEP_SERVERS:http://localhost:3002}
