spring:
  application:
    name: Identity-And-Access-Control-Server
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://ep-white-mountain-a2jkrsx3.eu-central-1.aws.neon.tech/google-club?sslmode=require}
    username: ${DATABASE_USERNAME:google-club_owner}
    password: ${DATABASE_PASSWORD:wrSROK5eA4vN}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:your-smtp-username}
    password: ${MAIL_PASSWORD:your-smtp-password}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS_ENABLE:true}

app:
  email:
    verification:
      token:
        expiryInSec: ${EMAIL_VERIFICATION_TOKEN_EXPIRY:86400}
        maxTokenGenerationInSec: ${MAX_TOKEN_GENERATION_IN_SEC:600}
  password:
    reset:
      token:
        expiryInSec: ${PASSWORD_RESET_TOKEN_EXPIRY:3600}
        maxTokenGenerationInSec: ${MAX_TOKEN_GENERATION_IN_SEC:600}
  CORS:
    ALLOWED-ORIGINS: ${CORS_ALLOWED_ORIGINS:*}
    ALLOWED-METHODS: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
    ALLOWED-HEADERS: ${CORS_ALLOWED_HEADERS:*}
    EXPOSED-HEADERS: ${CORS_EXPOSED_HEADERS:*}
    ALLOW-CREDENTIALS: ${CORS_ALLOW_CREDENTIALS:true}
    MAX-AGE: ${CORS_MAX_AGE:3600}
  depServers: ${DEP_SERVERS:http://localhost:3002}
  clients:
    web:
      amwc: ${AMWC:http://localhost:4200}